#!/usr/bin/env zsh

function zpack-list() {
    local item
    if [[ -n $__ZPACK_PLUGINS ]]; then
        __zpack_out_plain "Plugins:"
        for item in $__ZPACK_PLUGINS; do
            __zpack_out_plain "    $item"
        done
    fi
}

zpack-list $@
