#!/usr/bin/env zsh

function zpack-reset() {
    local dir
    for dir in ${ZPACK[cache_dir]}; do
        __zpack_out "Deleting '$dir'"
        rm -drf "$dir"
    done

    __zpack_out "Deleting compiled files"
    rm -f ${ZPACK[dir]}/functions/*.zwc(N)
    rm -f ${ZPACK[dir]}/*.zwc(N)

    __zpack_out "Restarting shell"
    exec $SHELL
}

zpack-reset $@
